sentences = [
    "The image features a giraffe standing in a dirt area, possibly in a zoo enclosure. The giraffe is looking at the camera, capt",
    "The image features a dirty bathroom with a white toilet sitting on a dirty floor. The toilet is positioned in the middle of the room",
    "The image features a woman sitting in a chair, wearing a black jacket and a white shirt. She appears to be a judge or a professional,",
    "The image features a large, round, reflective sign with the number \"66\" on it, likely representing a highway or a specific location. The sign",
    "The image depicts a busy city street with a large white bus driving down the road, surrounded by several other buses. The buses are positioned",
    "The image features a cityscape with a skyline of tall buildings, including a mix of skyscrapers and other structures. The buildings are situated",
    "The image features two small green trucks driving on a snow-covered road. One truck is positioned closer to the left side of the road",
    "The image features a blue and white train traveling down the tracks, with a car visible in the middle of the train. The train is passing by a rail",
    "The image features a blue and white train traveling down the tracks, with a clear blue sky above. The train is positioned in the middle of the scene",
    "The image features a small yellow and black bird perched on a thin tree branch. The bird is sitting on the branch, looking around and possibly observing its",
    "The image features a dirty, old toilet in a bathroom stall. The toilet is situated in the corner of the room, and it",
    "The image depicts a city street with a center divider, where a street sign is placed. The street sign is positioned in the middle of the",
    "The image features a small yellow house with a snow-covered roof, surrounded by a fence. The house is located in a snowy yard, and",
    "The image features a large, open-air tent with a triangular shape, providing a unique and comfortable outdoor space. The tent is situated on a pat",
    "The image captures a young man in a red and white uniform, jumping high in the air while performing a jumping exercise. He is wearing a",
    "The image features a group of three candy figurines, each representing a different character. One of the figurines is a bunny, while the other",
    "The image features a close-up of a purple flower with a yellow center, sitting in a field of green grass. The flower is the main focus of",
    "The image features a giraffe bending down to eat grass in a field. The giraffe is positioned in the center of the scene, with",
    "The image features a white toilet sitting on a sidewalk next to a wooden box. The toilet appears to be in a broken or damaged",
    "The image features a large, wild cheetah walking across a grassy field. The cheetah is the main focus of the scene, with its distinct",
    "The image features a train traveling down the tracks in a city, with a large building in the background. The train is positioned in the middle of the",
    "The image features a group of motorcyclists riding down a highway, with several motorcycles visible in the scene. The motorcyclists are",
    "The image depicts a busy street filled with various vehicles, including motorcycles, cars, and trucks. There are numerous people riding motor",
    "The image features a close-up of a tree filled with pink flowers, likely cherry blossoms. The tree is covered in a variety of p",
    "The image features a grassy field with several airplanes parked on it. There are three airplanes in total, with one being a small prop",
    "The image features a large sailboat with a tall mast and a long sail, floating on the water. The boat is positioned in the middle of",
    "The image features a large, old stone building with a distinctive dome-shaped roof. The building has a rustic appearance, and it appears to",
    "The image depicts a city street with a yellow line painted on the road, indicating a one-way street. There are several cars parked along the",
    "The image features a giraffe standing in a grassy field with a mountain in the background. The giraffe is positioned towards the center of the",
    "The image features a large green bus parked on the side of a street, likely in a city. The bus is adorned with a tropical theme,",
    "The image features a tall, skinny red and white striped structure, possibly a smokestack or a chimney, located in the middle of a",
    "The image features a sandy beach with a few footprints in the sand, indicating that someone has been walking along the shore. The sky above the beach",
    "The image features a young girl lying on a bed, accompanied by her orange cat. The cat is resting on the bed next to the girl, creating a",
    "The image features two giraffes standing in a grassy field, surrounded by rocks and dirt. One giraffe is positioned closer to the",
    "The image features a city street with a large bus parked on the side of the road. The bus is adorned with a painting of a man and",
    "The image features a beautiful scene of a vineyard with a large body of water in the background. The vineyard is filled with numerous vines,",
    "The image depicts a large group of people gathered in a room, with some of them wearing orange vests. They appear to be a diverse mix",
    "The image features a small yellow bird perched on the grass, looking around and possibly searching for food. The bird is positioned in the center of the scene",
    "The image is a black and white photo of a narrow pathway between two large rocks. The pathway is surrounded by trees, creating a serene and natural",
    "The image features a white butterfly perched on a leaf in a lush green forest. The butterfly is positioned in the center of the",
    "The image features a street sign on a pole, pointing towards a Jewish street. The sign is green and white, with a yellow arrow pointing to the right.",
    "The image features a beautiful nighttime scene of a bridge with a castle in the background. The bridge is illuminated by lights, creating a captivating",
    "The image features a large orange crane with a metal structure, likely a bridge or a building, in the background. The crane is positioned above a",
    "The image features a field of green grass with several white flowers blooming in the middle of it. The flowers are scattered throughout the field, with some closer to",
    "The image features a picturesque scene of a lake surrounded by a grassy field. Two people are standing near the lake, enjoying the view and the tran",
    "The image features a young man wearing a red and white shirt, walking on a track while holding a frisbee. He appears to be a",
    "The image features a small, clean bathroom with a white toilet and a white sink. The toilet is adorned with a red rib",
    "The image features a peaceful scene of a park with a wooden bench situated in the middle of a grassy field. The bench is positioned near",
    "The image features a dining table with a variety of food items arranged on it. There are three plates of food, including a plate of vegetables,",
    "The image features a black cat sitting on a table, looking at a glass of wine. The glass is placed in front of the cat, and the cat appears",
    "The image features a dining table with a plate containing two pieces of churros, a popular Spanish dessert. The churros are accompanied by a",
    "The image features a blue and white motorcycle parked outside a house, with an umbrella covering it. The motorcycle is positioned on the side",
    "The image captures a stunning view of a city at night, with its bright lights illuminating the skyline. The cityscape is filled with",
    "The image depicts a bustling city street with a group of people walking down the sidewalk. There are at least six people visible in the scene",
    "The image features a man sitting on a green park bench, wearing a tan jacket and sunglasses. He appears to be enjoying his",
    "The image features a man wearing a cowboy hat and riding a horse in a grassy field. The man is sitting on the horse, which is",
    "The image features a large group of bicycles parked next to each other on a dock near a large cruise ship. There are at least 1",
    "The image depicts a busy city street with several people riding bicycles. A woman is riding a bicycle with a dog in a",
    "The image depicts a small, clean bathroom with a white toilet and a sink. The toilet is located on the left side of",
    "The image features a small bird perched on a tree branch, possibly a baby koala. The bird is sitting on the branch, looking at the camera.",
    "The image captures a serene beach scene with a beautiful sunset in the background. The sun is setting over the ocean, casting a warm glow on",
    "The image features a field of blue flowers, predominantly purple, with some white flowers mixed in. The flowers are scattered throughout the field, creating a",
    "The image features a tree with a branch holding a cluster of pink flowers. The flowers are in various stages of blooming, creating a beautiful and colorful",
    "The image features a small brown frog sitting on a patch of dirt, surrounded by grass and rocks. The frog is positioned in the center of",
    "The image features a parking lot with several buses parked in a row. There are three buses in total, with one being larger and occupying",
    "The image features a pair of gold earrings displayed in a small, white, and silver box. The earrings are hanging from the box,",
    "The image features a wooden cutting board with a saying on it, \"Every day is a gift.\" The cutting board is placed on a table, and next to",
    "The image depicts a group of sheep running across a grassy field, with a dog chasing them. The sheep are scattered throughout the field, with",
    "The image features a small yellow and white airplane parked on a runway, with a mountain range in the background. The airplane is positioned on",
    "The image features a young man running on a track, wearing a red shirt and grey pants. He appears to be in the middle of a race",
    "The image features a group of people riding on a train that is traveling on tracks. The train is filled with passengers, and some of them are standing",
    "The image features a cozy living room with a wooden dining table surrounded by chairs. The table is set with candles, creating a warm and inv",
    "The image features a small bird standing on a tree branch near a body of water. The bird is positioned close to the water, possibly looking for food or",
    "The image features a river with a bridge crossing over it. The bridge is made of wood and has a metal fence on top. The fence is designed",
    "The image features a gold star with the word \"new\" written on it. The star is made of metal and has a chain attached to it. The star",
    "The image features a red and yellow vintage car with a surfboard on top of it, driving down a street. The car is parked on",
    "The image features a woman feeding a giraffe from a tree branch. The giraffe is standing close to the woman, and she is holding the",
    "The image features a black and white bird perched on a tree branch. The bird is positioned towards the center of the scene, with its wings spread out",
    "The image depicts a lively beach scene with a large body of water and a rocky shoreline. A group of people is walking along the",
    "The image features a train station with a blue and white train parked at the platform. The train is positioned on the left side of the scene, occup",
    "The image features a small dog sitting inside a cage on the back of a motorcycle. The dog appears to be enjoying its time on the motorcycle",
    "The image features a bathroom with a white sink and a mirror above it. The sink is situated in the middle of the bathroom, and the mirror is",
    "The image features a wooden dining table with a spoon and a glass of water placed on a napkin. The table is situated next to a window,",
    "The image features a snowy field with two people standing in the snow, flying a kite. The kite is soaring high in the sky, capt",
    "The image features two giraffes walking together in a dirt area, possibly a zoo enclosure. They are positioned close to each other, with",
    "The image features a yellow truck parked in a garage or warehouse, with its hood open. The truck is an old-f",
    "The image features a brown dog lying down on a couch, appearing to be sleeping. The dog's head is resting on a pillow,",
    "The image features a serene scene of a lake surrounded by trees and mountains. The lake is calm and still, reflecting the beauty of the landscape. The",
    "The image features a large body of water with a city skyline in the background. The city is situated on the other side of the water, creating a pictures",
    "The image features a large brick building with a stone wall, which appears to be a castle-like structure. The building has a row of arched windows,",
    "The image features a man standing in a grassy field, talking on his cell phone. He is positioned near the center of the scene. In the background",
    "The image depicts a busy city street with a woman walking across the street while carrying a handbag. She is wearing a dress and appears to be",
    "The image features a brown and white animal, possibly a fox or a dog, lying down on a grassy field. The animal is resting on its",
    "The image depicts a busy city street with a blue and yellow bus driving down the road. The bus is positioned in the middle of the scene,",
    "The image depicts a large group of people sitting in a room, possibly a conference hall or a courtroom. They are all focused on a screen,",
    "The image features a street corner with a pole holding up a street sign. The sign is displaying the names of two streets, 7th Avenue and West",
    "The image features a black and white traffic light with a \"Do Not Enter\" sign attached to it. The traffic light is positioned on a pole, and",
    "The image depicts a group of people standing in a parking lot, waiting to board a large white bus. There are several people in the scene,",
    "The image features a wooden bench situated in a grassy field, surrounded by a few rocks. The bench is positioned in the middle of the scene",
    "The image features a small train with a green and yellow engine, carrying a group of people on a track. The train is moving along the track, and there",
    "The image features a serene scene of a large body of water, likely a lake, with mountains in the background. The water is calm and reflective,",
    "The image features a close-up of a tree branch with several pink flowers blooming on it. The flowers are scattered across the branch, with some located",
    "The image features a large, old stone castle with a tall, pointed roof. The castle is surrounded by a lush green field, giving it a picturesque",
    "The image captures a busy street scene with several bicycles and their riders. There are at least five bicycles visible in the scene, with",
    "The image features a close-up of a white flower with green leaves, possibly a lily, growing on a tree. The flower is positioned in the",
    "The image shows a group of people gathered around a dining table, preparing food together. There are at least four people in the scene, with one person",
    "The image features a close-up of a beautiful pink flower with purple petals, surrounded by green leaves. The flower is the main focus of the",
    "The image features a large, old brick building with a tree in front of it. The building appears to be a castle-like structure, and it is surrounded",
    "The image features a single, beautiful red rose with a yellow center, sitting in a vase. The rose is the main focus of the scene, and it",
    "The image features a wooden dining table with a vase of flowers placed in the center. The vase contains a variety of flowers, including orange and white",
    "The image features a close-up of a beautiful pink flower with a yellow center, surrounded by green leaves. The flower is the main focus of the scene",
    "The image depicts a snowy road with a car driving down it. The road is covered in snow, and the car's tracks are visible in",
    "The image features a small green frog sitting on a rock in a stream. The frog is positioned in the center of the scene, surrounded by water",
    "The image depicts a group of people sitting around a long dining table, engaged in a meeting or discussion. There are at least 13 people",
    "The image features a close-up of a purple flower with a green stem, surrounded by green leaves. The flower is positioned in the center of the",
    "The image features a close-up of two pink roses, with one rose slightly larger than the other. The roses are positioned in the center",
    "The image features a black bird perched on a thin tree branch, looking up at the sky. The bird is positioned towards the center of the scene,",
    "The image features a young boy riding a toy horse in a public square, surrounded by a variety of oversized heads and faces. The boy is",
    "The image features a train traveling down the tracks, with a yellow and blue train engine leading the way. The train is moving along the tracks, which are",
    "The image features a purple motorcycle parked in a parking lot, surrounded by several cars. The motorcycle is positioned in the middle of the",
    "The image features a red and white fire hydrant standing in a grassy field. The hydrant is positioned in the middle of the scene, surrounded by",
    "The image captures a train station with a train moving swiftly down the tracks. The train is positioned in the center of the scene, and it appears",
    "The image features a seagull flying over a body of water, possibly the ocean. The bird is flying close to the water's surface, with its",
    "The image features a colorful rooster with a long tail, standing on a grassy field. The rooster is the main focus of the scene, occup",
    "The image features a lush green field with a variety of blue flowers, including bluebells and wildflowers, scattered throughout the scene. The flowers are",
    "The image features a large sailboat with a red flag flying high in the sky. The boat is surrounded by several other sailboats, creating a pictures",
    "The image features a giraffe standing in a grassy field with trees in the background. The giraffe is positioned towards the left side of the",
    "The image features a small, cluttered kitchen with a white stove top oven and a white refrigerator. The kitchen is filled with various",
    "The image depicts a busy city street with a large group of people walking around and engaging in various activities. There are several individuals carrying handbags",
    "The image depicts a bustling city street at night, with a group of people walking down the sidewalk. There are at least nine people visible",
    "The image features a tennis court with two women standing on it. One woman is wearing a black jacket and appears to be a tennis coach, while the",
    "The image features a man walking down a street at night, passing by a food truck. The food truck is selling various items, including hot dogs",
    "The image features a bird feeder hanging from a pole, with several birds perched on it. There are at least five birds visible in the scene,",
    "The image features a small bathroom with a white toilet situated in the corner of the room. The toilet is positioned next to a wall",
    "The image features a group of sheep grazing on a grassy hillside. There are four sheep in total, with one sheep standing closer to the left side",
    "The image features a street scene with a traffic light hanging above the road. The traffic light is currently displaying a red light, indicating that vehicles must stop.",
    "The image features a long bridge extending over a large body of water, with a cloudy sky above. The bridge is situated near a beach, and the water",
    "The image features two young men wearing red and black track uniforms, standing next to each other in a gym. They appear to be athletes,",
    "The image features a bed with a cat lying on top of a blanket. The cat is positioned between two stuffed animals, one on the left side",
    "The image features a large cruise ship docked at a pier, with its lights on. The ship is the main focus of the scene, occupying a",
    "The image features a group of four sheep standing in a field, with a mountain range in the background. The sheep are scattered across the field, with one sheep",
    "The image features a park with a wooden bench situated in the middle of a grassy field. The bench is positioned near a stone wall, which",
    "The image features a cityscape with a large airplane flying high above the buildings. The airplane is positioned towards the center of the scene, so",
    "The image features a yellow sports car parked in a parking lot, with a man standing next to it. The car is positioned in the middle of",
    "The image features a public restroom with three urinals lined up against a wall. The urinals are white and are placed at different heights, c",
    "The image features a small tree in a pot, placed on a tray or a plastic container. The tree is surrounded by several potted plants, creating",
    "The image features an old-fashioned cash register with a green top, sitting on a table. The cash register has a calculator built into",
    "The image features a woman sitting on a bench in a park, wearing a purple shirt. She appears to be looking at something, possibly a",
    "The image features a dirt road surrounded by trees, creating a serene and peaceful atmosphere. The road is lined with a wooden fence, adding",
    "The image features a close-up of a red flower, possibly a cherry blossom, with a few other flowers in the background. The red flower",
    "The image features a beautiful garden scene with a variety of flowers, including yellow and blue ones. The yellow flowers are scattered throughout the garden, with some located near",
    "The image features two giraffes standing next to each other in a room. They are positioned near a window, with one giraffe standing closer",
    "The image features a city street with a row of tall buildings in the background. The buildings are made of glass and steel, giving them a modern and sleek",
    "The image depicts a large, open restaurant with a group of people sitting at tables. There are several chairs and dining tables spread throughout the space",
    "The image features a statue of a man holding a shield, standing in front of a building. The statue is positioned in the foreground, with the building",
    "The image depicts a group of people sitting around a table, clapping their hands together in a meeting or conference setting. There are at least 1",
    "The image features a pink fire hydrant situated on a sidewalk near a tree. The fire hydrant is located in front of a house, and there",
    "The image features a group of cows in a grassy field, with some of them standing and others grazing. There are a total of five cows",
    "The image features a black and silver telephone booth on a sidewalk, with a sign on top of it indicating that it is a Wi-Fi hot",
    "The image features a large body of water with a beautiful sunset in the background. There are several cranes standing on the water's edge, with",
    "The image depicts a group of men in suits engaged in a conversation in a room. There are at least four men in the scene, with one",
    "The image depicts a bustling city street with a group of people walking down the sidewalk. There are at least 13 people visible in",
    "The image depicts a bustling restaurant with a large glass window showcasing the interior. There are several people walking around the restaurant, some of",
    "The image features a close-up of a yellow flower with a green center, possibly a daffodil, sitting in a field of grass. The flower",
    "The image features a large bird, possibly a heron, standing in a grassy field with its beak open. The bird is positioned near a nest",
    "The image depicts a bustling city street filled with people walking and enjoying the lively atmosphere. The street is adorned with numerous red",
    "The image features a bird perched on a branch near a body of water. The bird is standing on a tree branch, surrounded by a few other branches.",
    "The image captures a busy city street with a yellow double-decker bus driving down the road. Several people are walking on the sidewalk, with some",
    "The image features a large, clean bathroom with a white bathtub and a separate shower area. The bathtub is situated next to a window",
    "The image features a group of people riding bicycles in front of a church. There are five bicycles in total, with some riders we",
    "The image features a man dressed in a Santa Claus costume, standing in a bathroom and holding a red cup. He appears to be enjoying a",
    "The image features a white table with four bowls placed on it. The bowls are of various sizes and shapes, with one being larger and the others smaller",
    "The image features a single yellow tulip flower blooming in a grassy field. The flower is situated in the center of the scene, surrounded by l",
    "The image features a small bird, likely a duck, swimming in a body of water. The bird is surrounded by a lush green environment, with",
    "The image features a stop sign with a large portion of its paint chipped off, making it appear worn and faded. The stop sign is located in front",
    "The image features a man wearing a chef's outfit, standing in a kitchen and preparing food. He is focused on cooking, with a",
    "The image features a table with a variety of donuts, each with different toppings and decorations. There are three donuts in total, with one on",
    "The image features a small airplane flying high in the sky, with its wings spread out. The airplane is positioned in the middle of the scene,",
    "The image features a large, old-fashioned sailing ship docked at a pier. The ship is surrounded by several smaller boats, including a few",
    "The image features a large, old brick building with a pointed roof, resembling a castle or a church. The building has a distinctive red brick exterior",
    "The image captures a beautiful sunset over the ocean, with the sun setting behind a rocky outcrop. The sky is filled with clouds, creating",
    "The image captures a group of cyclists riding down a street, with a total of 13 bicycles visible in the scene. The cycl",
    "The image features a white toilet with a roll of toilet paper on the tank. The toilet is situated in a bathroom with a",
    "The image is a black and white photo of a fenced-in field with a few trees in the background. The field appears to be empty, with no",
    "The image depicts a group of people gathered in a large room, possibly a gymnasium or a stadium. There are at least 13 people",
    "The image features a large, ornate cathedral with a high vaulted ceiling and numerous stained glass windows. The cathedral has a long,",
    "The image features a large, old stone church with two tall towers and a cross on top. The church has a large arched window, and the to",
    "The image features a bathroom with a sink, toilet, and a mirror. The sink is located on the left side of the bathroom, while",
    "The image depicts a snowy street with a row of parked cars on the side. There are several cars parked along the street, with some",
    "The image features a large city with a skyline of tall buildings, including a few skyscrapers. The city is situated near a body of water",
    "The image features a person sitting at a dining table, surrounded by various food items. The person is using a cell phone, possibly checking messages or browsing",
    "The image depicts a busy city street filled with traffic, including cars and a motorcycle. There are several cars driving down the street, with some position",
    "The image features a bathroom with a white sink and a toilet situated next to it. The sink is positioned under a mirror, and there is",
    "The image features a large stained glass window in a church, showcasing a beautiful and intricate design. The window is adorned with a variety",
    "The image features a single yellow flower, possibly a daffodil, standing in a grassy field. The flower is positioned near the center of the",
    "The image features a blue and yellow train on a track, with a small Lego figure standing next to it. The train is positioned on the left side",
    "The image features a bathroom with two white sinks placed side by side. Each sink has a faucet, and there are multiple bottles placed around",
    "The image depicts a large herd of zebras and wildebeests grazing together in a grassy field. There are at least",
    "The image features a close-up view of a spoon resting in a bowl filled with a mixture of carrots and potatoes. The sp",
    "The image features three men sitting on chairs, engaged in a conversation. They are all dressed in suits, with one man wearing a tie. The",
    "The image features a close-up of a brown and white camel with a humorous expression on its face. The camel appears to be making a fun",
    "The image shows a man standing in a bathroom, using a urinal. He is wearing a blue hoodie and jeans, and appears to",
    "The image features a large body of water with a tall tower in the background. The tower is situated near the edge of the water, and it appears to be",
    "The image features a boat floating on a body of water, with a cloudy sky in the background. The boat is positioned in the middle of the scene",
    "The image features a man sitting on a bench, working on his laptop. He is wearing a hat and appears to be focused on his task. There",
    "The image features a large herd of zebras and wildebeests grazing together in a grassy field. There are at least 14",
    "The image features a bathroom with a white sink and three urinals lined up next to each other. The urinals are positioned in a row,",
    "The image features a large glass display case in a library, showcasing a stuffed bear on a wooden stand. The bear is positioned in the center",
    "The image captures a young man running on a track, wearing a black jacket and black pants. He appears to be in motion, possibly particip",
    "The image features a beautiful mountain landscape with a tree filled with pink flowers. The tree is located near the top of the mountain, and the flowers are scattered",
    "The image features a large building with a blue sign on its side, likely advertising an event or venue. The sign is positioned above a stop sign",
    "The image features a small, shaggy sheep standing in a grassy field. The sheep appears to be looking at the camera, and it is surrounded by",
    "The image features a black bird perched on a tree branch, possibly a crow. The bird is sitting on the branch, looking down at the ground below.",
    "The image features an old, rusted train car sitting on a dirt road. The train car is red and appears to be in a state of disrep",
    "The image features a small train with a group of people riding on it. The train is traveling down the tracks, and there are several passengers on board",
    "The image features a man wearing a black shirt and a microphone, sitting in front of a window. He appears to be smiling and enjoying",
    "The image features a group of police officers standing in a line, posing for a picture. There are a total of 12 officers in the group,",
    "The image features a grassy hillside with two sheep standing on it. One sheep is positioned closer to the left side of the hill, while the other",
    "The image features a large body of water with a city skyline in the background. The city is situated on a peninsula, with a long pier extending",
    "The image features a lizard lying on a rocky surface, possibly a stone or concrete ground. The lizard is positioned in the center of the scene",
    "The image features a wooden bench situated in a grassy area near a body of water. The bench is positioned on the grass, providing a comfortable",
    "The image features a giraffe standing on a rocky hillside, with a bird perched on its back. The bird is positioned near the center",
    "The image depicts a busy city street with a group of people walking down the sidewalk. There are at least five people visible in the scene, with",
    "The image features a close-up of a yellow flower with a yellow center, surrounded by a black background. The flower appears to be a daffodil",
    "The image features a large, tall building with a dome-shaped roof, situated in a city. The building has many windows, and some of them",
    "The image features a cozy dining room with a red and white checkered tablecloth on a dining table. The table is set with red nap",
    "The image depicts a busy city street with a large group of people walking down the sidewalk. There are at least 14 people visible in the",
    "The image features a small white flower, possibly a white rose, sitting in a field of green leaves. The flower is surrounded by a variety of green leaves,",
    "The image features a stunning view of the city at night, with the iconic Empire State Building towering over the cityscape. The building is lit",
    "The image depicts a group of people gathered in a kitchen, with a woman and a young boy being the main focus. The woman is feeding the",
    "The image features a man standing in a kitchen, cutting a piece of meat on a cutting board. He is using a knife to slice the meat, which",
    "The image features a small, cozy room with a bunk bed that has three beds in it. The beds are arranged in a way that allows",
    "The image features a tall building with a clock tower at the top, towering over a city at night. The building is lit up, and the sky above",
    "The image features a police officer standing next to a motorcycle, possibly a police motorcycle, in a parking lot. The officer is wearing a hel",
    "The image features a table with a variety of coffee-related items. There are two coffee mugs, one on the left side and the other on the right",
    "The image features a black and white cat standing on a snow-covered ground, looking at a wine glass filled with red wine. The cat appears to be",
    "The image features a close-up of a purple flower with green leaves, possibly a lilac, growing in a forest. The flower is surrounded by",
    "The image depicts a group of people sitting around a long dining table, engaged in a meeting or discussion. There are at least nine people visible in",
    "The image features a train with large windows, providing passengers with a beautiful view of a bridge and a river. The train has several chairs and dining tables",
    "The image features a picturesque town with a large, old building situated on a hill. The town is surrounded by a lush green forest, giving it a",
    "The image depicts a cozy kitchen with a dining table and chairs. The table is set with a vase of red flowers, adding a",
    "The image features a group of four giraffes standing in a grassy field. They are positioned in a line, with one giraffe on",
    "The image features a group of people gathered around a man who is speaking into a microphone. The man is wearing a suit and tie, and he appears",
    "The image captures a large passenger jet taking off from an airport runway. The airplane is flying low over a street, with a traffic light visible",
    "The image depicts a small bathroom with a toilet situated next to a sink. The toilet is positioned under a cabinet, and",
    "The image features a large truck driving down a highway, hauling a massive piece of construction equipment. The truck is positioned in the center of the",
    "The image features a group of seagulls flying over a body of water. There are five birds in total, with one bird flying higher in the sky",
    "The image features a woman standing on a tennis court, wearing a black jacket and a blue lanyard. She is holding a microphone and appears",
    "The image features a baker in a kitchen, carefully placing a piece of cake onto a plate. The cake is positioned on a tray,",
    "The image features a large, old-fashioned motorcycle on display, drawing the attention of several people. There are at least nine people in the scene",
    "The image features two giraffes standing next to each other in a grassy area. They are positioned close to a tree, with one gira",
    "The image features a black motorcycle parked on the side of a street. The motorcycle is positioned near the curb, and it appears to be",
    "The image features a close-up of a white flower with a yellow center, possibly a poppy. The flower is surrounded by a white background, which emphas",
    "The image depicts a narrow canal running through a city, surrounded by buildings on both sides. The canal is frozen, creating a picturesque winter scene",
    "The image features a birthday cake with a baseball cap on top of it, likely celebrating a baseball fan's birthday. The cake is",
    "The image captures a serene beach scene with a large body of water, likely the ocean, in the background. The water appears to be calm, and",
    "The image features a tree filled with purple flowers, creating a beautiful and vibrant scene. The tree is covered in a variety of pink and pur",
    "The image features a park setting with a bench situated in the middle of a grassy field. A black bird is perched on the bench, while",
    "The image features a colorful, abstract pattern with a mix of blue, pink, yellow, and orange hues. The pattern is composed of various shapes",
    "The image is a black and white photo of a large, old building with a clock tower. The building appears to be a church, as it has a ste",
    "The image features a brown dog lying on the ground, resting on a sidewalk. The dog is positioned near a hat, which is placed on the",
    "The image features a lush green field with a row of trees in the background. The trees are lined up, creating a beautiful and serene atmosphere.",
    "The image features a stop sign with graffiti on it, which reads \"war.\" The stop sign is located on a pole, and it is situated in",
    "The image features a large yellow school bus driving down a road, with a few people visible inside the bus. The bus is positioned in the middle of the",
    "The image features a large sailboat docked at a pier, with a beautiful sunset in the background. The boat is positioned in the center of",
    "The image features a small owl perched on a tree branch, looking around with its head tilted. The owl is surrounded by a few p",
    "The image features a brown and white owl flying through the air, with its wings spread wide. The owl is captured in mid-flight, so",
    "The image depicts a group of people sitting at a picnic table in a park, enjoying a meal together. There are several benches around",
    "The image is a black and white photo of a large, open field with a hill in the background. The field is mostly empty, with a few trees scattered",
    "The image features a close-up of a white flower with a delicate petal structure. The flower is positioned in the center of the frame, surrounded",
    "The image features a large orange and white cat sitting on a bed, which is covered with a red blanket. The cat appears to be looking at the camera",
    "The image features a red fire hydrant with a black hat sitting on top of it. The hat is placed on the fire hydrant in a way that it",
    "The image features a train station with a train stopped on the tracks. The train is positioned on the left side of the image, occupying a significant portion",
    "The image features a yellow school bus with a stop sign attached to the side of it. The stop sign is prominently displayed, making it easy for drivers",
    "The image depicts a residential street with a red stop sign prominently placed at the intersection. The street is lined with trees, providing a",
    "The image features a grassy field with two white sheep grazing on the grass. One sheep is positioned towards the left side of the field, while the",
    "The image depicts a large group of people gathered in a room, sitting on chairs and standing around. They are all focused on a television screen,",
    "The image features a wooden deck with several benches arranged in a row. There are five benches in total, with one located near the left side of the",
    "The image features a bathroom with two white sinks placed side by side. The sinks are accompanied by mirrors above them, providing a convenient space for",
    "The image features a group of people standing together in a room, posing for a picture. There are at least 13 people in the group, with",
    "The image features a large cat sitting on top of a wooden table, possibly a bar counter. The cat appears to be looking at something, possibly a person or",
    "The image features a beautiful pink flower with a large, round center, sitting in a field of green grass. The flower is the main focus of the scene",
    "The image depicts a bustling city street with a large, old cathedral towering over the surrounding buildings. The cathedral is located at the",
    "The image features a large, bright orange truck with a black front end, parked on a dirt road. The truck has a distinctive appearance",
    "The image features a small green tractor with a large blade on the front, sitting in the snow. The tractor is positioned on a snow-",
    "The image features a large sailing ship with a tall mast and a prominent red flag at the top. The ship's mast is adorned",
    "The image features a large, dry grass field with a sandy beach nearby. The grass is tall and brown, giving the impression of a desert-like landscape",
    "The image features a woman wearing a straw hat and sunglasses, standing on a boat in the water. She is smiling and appears to",
    "The image captures a serene beach scene with a few people walking along the shore. There are three people visible in the scene, with one person closer to",
    "The image depicts a busy city street filled with people walking and riding motorcycles. There are several pedestrians walking along the sidewalk",
    "The image features a young girl sitting on a yellow bench outside a store. She is wearing a backpack and has a purple bag in her hand",
    "The image depicts a snowy forest with a group of trees covered in snow. The trees are tall and have snow on their branches, creating a ser",
    "The image features a tall, old stone tower with a cross on top, towering over a lush green hillside. The tower is surrounded by trees,",
    "The image features a giraffe standing in a watering hole, drinking water from a pond. The giraffe is surrounded by several birds,",
    "The image features a white toilet with a full tank of ice cubes inside. The ice cubes are scattered throughout the tank, creating a unique and",
    "The image features a person wearing a ring on their finger, with the ring being the main focus of the scene. The person is also holding a cell phone",
    "The image features a statue of a man riding a horse, positioned on a stone pedestal. The statue is located in a park, surrounded by",
    "The image features a dirt path in a park, with a bench situated on the side of the trail. The bench is positioned near the center",
    "The image features a window with a drawing of a person and two ghosts on it. The drawing appears to be a cartoon-like representation of a person",
    "The image features a bathroom with a white toilet positioned next to a sink. The sink is located on the left side of the bathroom,",
    "The image features a young girl sitting on a stone bench in a park. She is wearing a pink shirt and appears to be enjoying her",
    "The image features a dog sitting in the driver's seat of a blue truck, seemingly driving the vehicle. The dog appears to be enjoying the",
    "The image features a bathroom with a white toilet sitting on a checkered floor. The toilet is positioned in the center of the room",
    "The image features a young child, possibly a toddler, standing on a wooden bench in a public area. The child is smiling and appears to",
    "The image features a close-up of a dandelion flower, showcasing its delicate and intricate structure. The flower is surrounded by numerous",
    "The image features a small, well-equipped kitchen with a stainless steel countertop and a stove top oven. The kitchen is filled with",
    "The image depicts a bathroom with two sinks, one on the left and the other on the right side of the room. The sinks are",
    "The image features a street sign with a blue background, indicating the intersection of 3rd Avenue. The sign is positioned above a traffic light, which is",
    "The image captures a surfer skillfully riding a wave on a surfboard. The surfer is in the middle of the wave, displaying their",
    "The image depicts a street scene with a white car driving down the road. There are several street signs visible in the scene, including a large sign with",
    "The image depicts a group of people gathered around a dining table, engaged in a meeting or discussion. There are five people in the scene, with",
    "The image features a large boat traveling across a large body of water, possibly a river or a lake, with a city skyline in the background. The",
    "The image features a bathroom with a large, ornate bathtub situated in the center of the room. The bathtub is surrounded by a tile",
    "The image features a table with a variety of children's toys and items, including a green water toy, a green water cannon, and a",
    "The image features a close-up of a flower with a pinkish hue, surrounded by green leaves. The flower is positioned in the center of",
    "The image features a red double-decker bus driving down a street, with another bus visible in the background. The red bus is quite large and occupies",
    "The image features a festive scene with a variety of Easter decorations. There are several large stuffed animals, including a large rabbit and a large",
    "The image features a dining table with a plate of food and a cup of coffee on it. A seagull is standing on the table, seemingly",
    "The image features a blue and white bird perched on a branch in a cage. The bird is sitting on top of a wooden branch, surrounded by a",
    "The image features a table with a variety of toys and items, including a green crocodile toy, a bottle of wine, and a few",
    "The image features a group of motorcycles parked in a parking lot, with one of them being a police motorcycle. A man is standing next",
    "The image features a public restroom with three urinals lined up against a wall. The urinals are placed at different heights, catering to",
    "The image features two mountain goats standing on a road, possibly in a rural area. They are facing each other, possibly engaging in a fight or play",
    "The image features a large, long, and thick snake coiled up on the ground, surrounded by rocks and grass. The snake appears to be a",
    "The image features a bird perched on a tree branch, surrounded by a few berries. The bird is positioned in the middle of the scene, with",
    "The image features a man kneeling down next to a bicycle, taking a picture of the bike with his cell phone. The man is wearing",
    "The image features a man standing in a kitchen, preparing food. He is wearing a hat and glasses, and he is surrounded by various kitchen items",
    "The image features a small, dirty toilet with a white seat and a hole in the middle, placed on a tiled floor. The toilet",
    "The image features two giraffes standing on a grassy hillside, with one giraffe positioned closer to the left side of the scene and",
    "The image features a woman standing on a rocky hill, looking at the camera. She is wearing a scarf and appears to be enjoying the view",
    "The image features a man sitting in a room with a greenish tint, possibly a kitchen or a dining area. He is seated at a d",
    "The image features a brick wall with a vine growing on it, covered in white flowers. The vine is climbing up the wall, creating a beautiful",
    "The image features a gold heart-shaped locket sitting on a clear plastic stand. The locket is placed on a table, and it appears to",
    "The image features a tree with a large mushroom growing out of it. The mushroom is located on the side of the tree, and it appears",
    "The image features a close-up of a white flower with a yellow center, possibly a daisy. The flower is surrounded by a few other white flowers,",
    "The image features a large white boat docked at a pier, with a smaller boat nearby. The white boat is positioned in the middle of the scene,",
    "The image features a small blue and white airplane parked on a runway. The airplane is positioned in the center of the scene, with its",
    "The image features a colorful, tie-dye shirt with a design of six teddy bears in various colors. The teddy bears are",
    "The image features a young child, possibly a baby, sitting in a bathroom sink and crying. The child is looking at their reflection in the mirror,",
    "The image features a person holding a leaf in their hand, possibly in a dark room. The leaf appears to be a dead leaf, and the person is position",
    "The image features a large building with a sign that reads \"Dark Angel.\" The building has a prominent clock on its side, and there are several people walking",
    "The image features a bathroom with two mirrors mounted on the wall, one above the other. The mirrors are positioned above a sink, which is",
    "The image features two green robotic figures standing on a bridge, each holding a fishing rod. The robots are positioned close to each other, with",
    "The image features a red stop sign located near a railroad track. A train is passing by on the tracks, with several cars visible in the background. The",
    "The image features a beautiful garden with a variety of yellow flowers blooming in the sunlight. There are several yellow flowers in the foreground, with some of",
    "The image depicts a small, dark kitchen with a window that allows natural light to enter. The kitchen is equipped with a sink, an oven",
    "In the image, a woman is handing a man a flyer while standing on a sidewalk. The man is holding a booklet in his hand,",
    "The image depicts a small, clean bathroom with a white bathtub and a white toilet. The bathroom features a shower with",
    "The image features a small bathroom with a white toilet positioned next to a shower stall. The shower stall has a glass door",
    "The image features a woman driving a car with a group of seagulls perched on top of it. There are five birds in total, with some",
    "The image features a narrow alleyway between two buildings, with a small stream of water flowing through it. The alleyway is lined with trees",
    "The image features a woman and a young girl in a kitchen, both engaged in cooking activities. The woman is standing near the sink, while the girl is",
    "The image features a small bird perched on a tree branch, looking downward. The bird is positioned near the center of the scene, with its wings",
    "The image depicts a group of people gathered around a food truck, which is parked in a parking lot. There are several people standing and",
    "The image features a red train traveling down the tracks, surrounded by a beautiful landscape. The train is positioned in the middle of the scene, with a",
    "The image features a white plate filled with a delicious meal, including a hamburger, french fries, and a pickle. The plate",
    "The image features a blue vintage car driving down a busy street in a city. The car is passing by a traffic light, and there are several other",
    "The image features a tree with a reflection of its branches in the water. The tree branches are visible in the water, creating a beautiful and serene scene.",
    "The image features a wooden table with a bowl and two cups placed on it. The bowl is positioned towards the left side of the table,",
    "The image features a snow-covered street corner with a traffic light and a street sign. The traffic light is covered in snow, and the street sign is",
    "The image features a large, colorful parade float with a man dressed in a costume, possibly a jester or a masked figure, standing on",
    "The image features a man standing in front of a red telephone booth, talking on his cell phone. He is wearing sunglasses and appears",
    "The image features a motorcycle parked in front of a garage door, which is currently open. The motorcycle is positioned close to the door,",
    "The image features two young children, a boy and a girl, sitting on toilets in a bathroom. The boy is on the left side of the",
    "The image features a large bird, possibly a hawk or an eagle, flying over a body of water. The bird is soaring high in the",
    "The image depicts a large, well-equipped kitchen with a wooden dining table and several chairs. The table is surrounded by chairs,",
    "The image features a beautiful beach scene with a row of lawn chairs and umbrellas set up on the sand. There are numerous chairs and",
    "The image features a woman sitting at a dining table, smiling and holding a plate with a small piece of cake on it. She is wearing",
    "The image features a blue wall with a mural painted on it, depicting a face with a big smile and a red tongue. The face is surrounded",
    "The image features a large, old-fashioned building with a red and white facade. The building has a sign on the side, indicating that it",
    "The image features a red pickup truck parked on a grassy field, surrounded by other vehicles. The red truck is the main focus of the",
    "The image features a grassy field with a giraffe and two ostriches. The giraffe is standing near the center of the field,",
    "The image features a lonely beach with a red and white bus parked on the sand. The bus is positioned near the center of the scene, and",
    "The image features an old, dirty, and rusted truck parked on the side of a street. The truck is positioned next to a yellow",
    "The image depicts a train station with a train passing through a tunnel. Several people are waiting on the platform, some of them carrying luggage.",
    "The image features a large propeller airplane flying high in the sky. The airplane is white and blue, with a prominent blue stripe on its side",
    "The image features a white toilet sitting on a wooden floor, with a black speaker placed next to it. The toilet is positioned in the",
    "The image features a white toilet situated in a bathroom. The toilet is positioned under a picture frame, which is mounted on the wall",
    "The image features a vase filled with a variety of flowers, including tulips and daffodils. The vase is placed on a table,",
    "The image depicts a conference room filled with people sitting in chairs and listening to a man giving a presentation. The man is standing at the front of",
    "The image features a motorcycle parked under a red and white roofed structure, which appears to be a shed or a small building. The motorcycle is",
    "The image depicts a group of people gathered in a kitchen, with a woman feeding a man a spoonful of food. The man is se",
    "The image features a large tree with a thick trunk and a mossy, rocky bark. The tree has a few mossy patches",
    "The image features a dining table with two birds, possibly seagulls, standing on it. The birds are fighting over food on the table, which",
    "The image features a kitchen counter with various items on it. There is a bottle of wine prominently placed on the counter, surrounded by a few app",
    "The image features a man holding a sign that reads \"Manchester Vs. Travailer,\" standing in a crowd of people. The man is we",
    "The image features a close-up of a group of white flowers, possibly daffodils, growing in a grassy field. The flowers are in various",
    "The image features a public restroom with a white toilet situated in the corner of the room. The toilet is equipped with a handic",
    "The image features a young child sitting at a dining table, playing with a toy train set. The child is focused on the train, which is placed",
    "The image features a purple skateboard placed on the aisle of a bus, likely during a school trip. The bus is filled with several ch",
    "The image features a white pickup truck parked in a field, with a bride and groom sitting in the back of the truck. The",
    "The image features a beach scene with a large log lying on the sand, surrounded by rocks. The log appears to be washed up on the shore, possibly",
    "The image features a brown leather handbag with a gold buckle, placed on a white background. The handbag is open, revealing its interior",
    "The image features a wall with a shelf holding a variety of hats. There are three hats in total, with one placed on the left side of",
    "The image features a man wearing glasses and a white shirt, standing in front of a microphone. He appears to be giving a speech or presentation",
    "The image captures a man riding a motorcycle down a street, with the motorcycle in motion. The man is wearing a helmet and a",
    "The image features a large city skyline with a beautiful view of the ocean. The city is situated on the coast, with a long pier extending out into the",
    "The image captures a serene scene of a sunset over a body of water, with a rocky shoreline visible in the foreground. The",
    "The image features a white background with a variety of items placed on it. There is a blue cup, a blue towel, and a blue blanket,",
    "The image is a black and white photograph of a tree with a large, gnarled trunk. The tree is located near a path, and there are",
    "The image features a street corner with a street sign and a traffic light. The street sign is positioned above the traffic light, and both are mounted on a",
    "The image features a street with a crosswalk painted on it, surrounded by a variety of colorful barrels and pots. There are several potted",
    "The image is a black and white illustration of a bathroom featuring a yellow bathtub, a toilet, and a sink. The batht",
    "The image depicts a bathroom in the process of being remodeled. The toilet is placed on the floor, and the sink is also",
    "The image features a large, old, and abandoned building with a grassy field surrounding it. The building appears to be in a state of disrepair,",
    "The image features a black and white photograph of two cats sitting in a chair. One cat is sitting on the left side of the chair, while the other",
    "The image features a lively scene at a video game arcade, where two children are playing a racing game on a motorcycle. They are both sitting on",
    "The image depicts a dirty bathroom with a toilet and a sink. The toilet is located in the middle of the room, while",
    "The image depicts a busy city street with a school bus driving down the road. The bus is positioned in the middle of the scene, surrounded by",
    "The image features a close-up of a blurry flower, possibly a cherry blossom, with a white background. The flower is surrounded by",
    "The image features a parking lot with a row of wooden posts and a speed limit sign. The parking lot is situated near a body of water, possibly",
    "The image features a small bird perched on a tree branch, surrounded by a few berries. The bird is positioned in the center of the scene,",
    "The image features a red double-decker bus driving down a street, surrounded by a few cars. The bus is quite large and occupies a significant portion",
    "The image features a beautiful waterfront view of a city with a large body of water in the foreground. A row of tall buildings, including apartment complex",
    "The image features a yellow fire hydrant situated on the side of a street, with a black truck parked nearby. The truck is positioned in",
    "The image features a harbor with several boats docked in the water. There are at least five boats visible, with one boat being larger and more prominent in",
    "The image features a giraffe standing in a grassy field surrounded by trees. The giraffe is positioned in the center of the scene, with",
    "The image features a dog standing on a rocky beach near the water, looking out at the ocean. The dog appears to be enjoying the view and the",
    "The image features a park setting with a group of people sitting on a wooden bench under a tree. There are four people in total, with two of them",
    "The image is a black and white photo of a man wearing a suit and tie, standing in a doorway. He appears to be dressed in business att",
    "The image depicts a large group of people gathered in a room, sitting on chairs and clapping their hands. They are attending a meeting or",
    "The image features a close-up of a purple flower with a yellow center, surrounded by green leaves. The flower is in the foreground, and the",
    "The image features a large body of water with a marina filled with numerous boats of various sizes. The boats are docked in a line, creating a pictures",
    "The image features a white sheep lying down in a grassy field, with its head resting on the ground. The sheep appears to be relaxed and enjo",
    "The image depicts a large, grassy field with a group of people enjoying a day outdoors. There are at least 13 people",
    "The image features a white cat sitting on top of a black suitcase. The cat appears to be relaxed and comfortable, occupying a significant portion of the",
    "The image depicts a train station with a train on the tracks, surrounded by a large, open building. The train is positioned in the middle of",
    "The image features a sandy beach with a path leading towards the ocean. The path is surrounded by tall grass, giving it a secluded and serene atmosphere",
    "The image features two young men sitting next to each other at a table, both using a green laptop. They appear to be engaged in a shared activity, possibly",
    "The image depicts a narrow cobblestone street in a small town, surrounded by old buildings. The street is lined with a fence on",
    "The image features a long row of trees with their branches and leaves visible. The trees are lined up along a path, creating a serene and peaceful",
    "The image features a large, ornate church with a wooden altar and a stained glass window. The altar is situated in the center of the room",
    "The image features a large white bird, possibly a seagull, flying over a body of water. The bird is captured in mid-flight, with",
    "The image features a large, old stone church with two towers, one on the left and one on the right side. The church has a clock on the",
    "The image features a snow-covered park with a row of benches lined up along a path. The benches are covered in a thick layer of",
    "The image depicts a city street with two white trucks parked on the side of the road. One truck is positioned closer to the",
    "The image depicts a snowy forest with a pathway leading through the trees. The path is covered in snow, and the surrounding trees are also covered",
    "The image depicts a group of people gathered around a long table, engaged in a meeting or discussion. There are five people in total, with some sitting",
    "The image features a mother sheep and her baby standing in a grassy field. The baby sheep is positioned close to the mother, and they are both looking",
    "The image features two men standing on a rocky hillside, each holding a bicycle. They are likely taking a break from their ride, enjoying",
    "The image features a traffic light hanging from a wire, with two other traffic lights positioned below it. The traffic lights are situated in a clear blue sky",
    "The image features a bathroom with two white sinks placed side by side on a wooden counter. The sinks are accompanied by a mirror above them, and",
    "The image features a bathroom with a white sink and a mirror above it. The sink is accompanied by two faucets, one on the left side and",
    "The image features a large sub sandwich cut in half, placed on a white plate on a dining table. The sandwich is filled with meat and veget",
    "The image features a man in a green shirt and orange boots standing next to a pool of water. He is interacting with a seal, possibly",
    "The image features three sheep standing on a snow-covered hill. They are positioned close to each other, with one sheep on the left, another in",
    "The image features a clean and well-maintained bathroom with a walk-in shower stall. The shower is equipped with a glass",
    "The image features a large, rusty anchor sitting on a concrete slab near a body of water. The anchor is positioned close to the water's",
    "The image features a white purse placed on a table, accompanied by a variety of items. There are two books, one on the left side and the other",
    "The image features a close-up of a flower bud with a yellow center, surrounded by white petals. The flower is located on a branch, and the",
    "The image features a park bench covered in frost and ice, with a black hat sitting on the back of the bench. The bench is located",
    "The image features two pears sitting on a table, placed next to each other. The pears are positioned in a way that they appear to be facing",
    "The image depicts a city street with a tall brick building on the corner. A man is walking down the sidewalk in front of the building, holding",
    "The image features a train station with a train on the tracks. A man is standing in the doorway of the train, holding a cell phone and looking out",
    "The image features a large body of water with a city skyline in the background. There are several boats of various sizes scattered across the water, some closer to",
    "The image features a man standing outside a sandwich shop, holding a small dog on a leash. The man is wearing a blue jacket and appears",
    "The image features a shirtless man sitting on a wrestling mat, wearing a red and yellow belt. He appears to be a wrestler,",
    "The image features a beautiful white flower with red dots, possibly a cherry blossom, blooming in a tree. The flower is surrounded by a",
    "The image features two stuffed teddy bears, one dressed in a black dress and the other in a white shirt and tie. They are standing next",
    "The image captures a man riding a motorcycle down a street, surrounded by a crowd of people watching him. There are at least 13 people",
    "The image features a group of four trucks racing on a dirt track, with one of them taking a sharp turn. The trucks are closely",
    "The image features a person wearing a suit and standing in a blue light tunnel. The person appears to be a motorcycle rider, as they are we",
    "The image features a man lying on a bed with his back facing the camera. He has a prominent back muscle, which is visible as he lays down",
    "The image features a blue and yellow train traveling down the tracks, passing by a forest and a hillside. The train is positioned in the middle of",
    "The image features a large collection of various locks and keys, creating a unique and intriguing display. The locks are arranged in a visually appe",
    "The image features a large, majestic castle with a moat surrounding it. The castle is situated on a hill, and the moat is filled with water",
    "The image features a white bicycle parked on a sidewalk, surrounded by several statues. The bicycle is positioned in the center of",
    "The image features a street corner with a large signpost displaying various street names and directions. The signpost is located near a traffic light, which is currently showing",
    "The image features a large brick wall with a tree growing through it. The tree is situated in the middle of the wall, creating a unique and interesting visual effect",
    "The image features a lone giraffe walking across a grassy field, with its long neck and legs prominently visible. The giraffe is",
    "The image features a large yellow and blue train engine sitting on the tracks, with a blue and yellow caboose behind it. The train is positioned on",
    "The image features a small green tractor with a yellow front tire, parked in a snowy driveway. The tractor is surrounded by a significant",
    "The image features a group of five men dressed in suits and ties, standing side by side in front of a wall. They appear to be politicians",
    "The image features a close-up of a beautiful flower with a yellow center, surrounded by green leaves. The flower is positioned in the center of the frame",
    "The image depicts a man walking down a sidewalk next to a large pile of trash, which includes various cups, bottles, and",
    "The image features a bathroom with a white toilet and a bathtub. A cat is lying on the floor in front of the toilet",
    "The image features a young girl sitting on a park bench, covering her face with her hands. She is wearing a pink dress and appears to be",
    "The image features a stone monument with a statue of a hand on top of it. The hand statue is positioned in the middle of the monument, and it",
    "The image features a large glass window on a building, showcasing a mural of a cityscape. The mural includes a clock tower, a",
    "The image features a small bird perched on a tree branch, surrounded by green grass. The bird is positioned near the center of the scene, with its",
    "The image captures a beautiful sunset over the ocean, with the sun setting behind the horizon. The sky is filled with clouds, creating a dramatic back",
    "The image features a dining table with a large white plate filled with various desserts. The plate is topped with a delicious cake, surrounded",
    "The image captures a serene scene of a frozen lake at sunset, with a person standing on the ice. The sky is a beautiful shade",
    "The image features a cat lying on a bed, with a book placed next to it. The cat appears to be looking at the book, possibly intrigued",
    "The image features a large, ornate building with a dome and four towers, likely a mosque or a church. The building is surrounded by a",
    "The image features a sign for Mystic Blue Signs, which is a business that specializes in creating and selling signs. The sign is prominently",
    "The image depicts a group of people sitting around a long table, engaged in a meeting or discussion. There are at least nine people visible in the scene",
    "The image captures a beautiful sunset over a city skyline, with the sun setting behind a large building. The sky is filled with a warm glow",
    "The image depicts a small bathroom with a white toilet situated next to a bathtub. The toilet is positioned on the",
    "The image features two giraffes standing next to each other in a zoo enclosure. They are positioned near a fence, which separates them",
    "The image features a single white flower, likely a daffodil, sitting in the middle of a green plant. The flower is surrounded by a few leaves",
    "The image features a brown dog sticking its head out of a car window, enjoying the breeze and the view. The dog appears to be looking",
    "The image depicts a busy city street with a mix of vehicles and pedestrians. There are several cars, including a truck, parked",
    "The image depicts a group of people gathered around a table, working together on a project. There are at least 11 people in the scene,",
    "The image features a black pickup truck parked on a grassy area near a building. The truck is equipped with large tires, giving",
    "The image features a large commercial airplane flying high in the sky above a city. The airplane is positioned towards the center of the scene, with its",
    "The image features a close-up of a beautiful pink and white flower with a yellow center. The flower is surrounded by a few petals, giving it",
    "The image depicts a busy restaurant kitchen with several chefs working together to prepare food. There are five people in the kitchen, with one chef standing near",
    "The image features a large dining room with a long wooden table surrounded by numerous chairs. The chairs are arranged in various positions around the table, creating",
    "The image features a train station with a train stopped at the platform. The train is positioned on the left side of the image, occupying a significant portion",
    "The image features a large, white flower with a delicate, curled petal structure. The flower is positioned in the center of the frame, and",
    "The image features a clean and well-organized kitchen with wooden cabinets and a white refrigerator. The kitchen is equipped with a sink,",
    "The image depicts a busy city street filled with traffic, including cars and a truck. There are several cars driving down the street, with some position",
    "The image features a large, old brick building with a tall, round tower at the top. The building appears to be a castle-like structure, possibly a",
    "The image features a close-up of a flower with a green stem, possibly a tulip, sitting in a vase. The flower is surrounded by",
    "The image features two motorcycles parked side by side on a street. The motorcycles are positioned close to a brick wall, with one motor",
    "The image features a giraffe standing in a dirt field, with its head raised and looking around. The giraffe is positioned in the center",
    "The image depicts a busy city street with several people walking down the sidewalk. Among them, a man in a suit is crossing the street, while",
    "The image features a bathroom with a toilet positioned in the center of the room. Above the toilet, there is a booksh",
    "The image captures a skateboarder performing a trick in mid-air at a skate park. The skateboarder is in the center of",
    "The image shows a garbage truck parked on the side of a street, with two men standing next to it. One of the men is wearing a",
    "The image features a young girl standing on a sidewalk, playing with a fire hydrant. She is pointing at the hydrant, possibly enjoying her time",
    "The image features two giraffes standing close to each other in a grassy field. They are positioned near a stone wall, which adds a natural",
    "The image features a small bird perched on a thin tree branch. The bird is sitting on the branch, surrounded by green leaves, and appears to be looking",
    "The image features a large blue and white airplane on a runway, preparing for takeoff. The airplane is positioned in the middle of the",
    "The image features a white butterfly perched on a leaf, possibly a maple leaf, in a forest setting. The butterfly is positioned",
    "The image depicts a large, old building with a dome-shaped roof, surrounded by trees. The building appears to be a church, and",
    "The image features a close-up of a plate with a stack of chocolate candies, including a chocolate cake, placed on a d",
    "The image features a horse-drawn carriage with two horses, one on the left and the other on the right, pulling the carriage down a street. A",
    "The image depicts a pile of discarded electronics and furniture, including a TV, a computer monitor, and a chair. The TV is",
    "The image features a large, open gate with a fence, leading to a lush green field. The gate is open, allowing for a clear view of",
    "The image features a large city skyline with a boat floating on the water near the shore. The boat is positioned in the middle of the scene, and",
    "The image features a small child standing in front of a statue of a woman, possibly a witch, on a cobblestone street. The child appears",
    "The image depicts a group of people gathered in a room, possibly a conference room or a courtroom. There are four people in the scene, with",
    "The image features a picturesque scene of a large castle with a moat and a bridge. The castle is surrounded by a beautiful landscape, including a river and",
    "The image features a fire hydrant with a chain on it, located on a sidewalk. The fire hydrant is situated near the curb, and the",
    "The image is a black and white photograph of a train traveling down the tracks, with smoke billowing from its engine. The train is moving along the",
    "The image depicts a group of people gathered in a room, with some sitting at a table and others standing. A man in a pink shirt",
    "The image features a blue recycling bin with graffiti on it, located on the side of a street. The graffiti consists of a number",
    "The image features a large, round, blue and red painting with a swirling design. The colors in the painting are predominantly blue and red,",
    "The image captures a beautiful nighttime scene with a cityscape in the background. A tall building stands prominently in the distance, and a l",
    "The image depicts a picturesque town situated on a hillside, surrounded by a lush green forest. The town is built on a rocky hill",
    "The image features a table with a basket filled with various items, including a bottle of wine, a wine glass, and a few books. The basket is",
    "The image shows a person preparing food on a grill, with several hamburgers and sandwiches being cooked. There are at least five",
    "The image features a man in military fatigues, wearing a gas mask, standing next to a large truck. He is holding a hose connected",
    "The image features a street sign with multiple directions pointing towards different locations. The sign is situated in front of a tree, making it easily visible for passersby",
    "The image features a giraffe standing in a lush green forest, surrounded by trees and bushes. The giraffe is positioned in the center",
    "The image features a sandy beach with a grassy hillside, where a row of wooden fences is placed to keep the grass in check. The f",
    "The image features a close-up of a purple flower with a pink center, surrounded by green leaves. The flower is positioned in the center of",
    "The image features a bathroom with a large sink and a mirror above it. The sink is situated under a chandelier, adding a touch of eleg",
    "The image features a close-up of a flower with a long stem, showcasing its intricate details. The flower is surrounded by green leaves, creating",
    "The image features a large stone archway with a carved inscription on it, likely a monument or a historical site. The archway is situated in front",
    "The image features a kitchen with a bicycle parked inside, leaning against the counter. The kitchen is equipped with a sink, an oven",
    "The image features a close-up of a pink flower with white petals, possibly a cherry blossom, sitting in a field of green grass",
    "The image features two giraffes in a grassy field, standing next to each other. One giraffe is positioned closer to the left side",
    "The image depicts a city street with a woman walking down the sidewalk, carrying a handbag. She is walking past a building with a large bill",
    "The image features a young child sitting at a dining table, eating a bowl of spaghetti. The child is focused on enjoying the me",
    "The image depicts a large, open room with a high ceiling, likely a lobby or a store. There are several people in the room",
    "The image features a close-up of a flower with a purple center and yellow petals. The flower is surrounded by green leaves, creating a vibr",
    "The image features a giraffe standing in a dry grass field, surrounded by trees. The giraffe is positioned in the center of the scene,",
    "The image features a man walking down a street in front of a large, illuminated sign for Radio City Music Hall. The man is wearing a black",
    "The image features a serene scene of a large body of water with a beautiful sunset in the background. The sun is setting over the water, casting a",
    "The image features three men sitting on chairs, engaged in a conversation. They are all dressed in suits, with one man wearing a tie. The",
    "The image features a tree with a cluster of white flowers blooming on its branches. The flowers are scattered throughout the tree, with some located closer to the top",
    "The image features a brown and white butterfly perched on a leaf, possibly a maple leaf. The butterfly is positioned in the center",
    "The image depicts a cluttered kitchen counter with various cooking utensils and dishes. There are multiple pots and pans on the",
    "The image features a tree with a thick, mossy trunk and branches covered in pink flowers. The tree is located in a forest, surrounded by",
    "The image features a bathroom with a white bathtub situated next to a wall. Above the bathtub, there are two pictures hanging on",
    "The image features two young girls standing next to a fire hydrant, playing and enjoying the water shooting out of it. They are both smiling and having",
    "The image features a beach scene with a couple standing close to the water, enjoying the view. The couple is positioned near the center of the scene,",
    "The image features a white toilet with a sticker on the lid, indicating that it has been sterilized. The toilet is situated in",
    "The image features a man and a woman sitting at a dining table, engaged in a discussion. The man is pointing at a large map placed on the table",
    "The image features a small red and black frog sitting on a rock. The frog is positioned in the center of the scene, with its legs spread",
    "The image depicts a city street with a two-way street sign on the side of the road. The sign is positioned near a tree, and",
    "The image features a large aquarium filled with a variety of fish swimming around in the water. There are at least 14 fish visible in the scene",
    "The image features a large outdoor dining area with numerous tables and chairs arranged under a canopy. The tables and chairs are spread out, creating",
    "The image depicts a horse race track where a horse is being held by two men. One man is on the left side of the horse, while the",
    "The image features a man in a white shirt and hat, flying a model airplane in a field. The man is holding the remote control for the model",
    "The image features a city street with a row of food trucks parked along the side of the road. There are several people walking by the food tr",
    "The image features a large orange and black train engine sitting on the tracks, with a sign nearby. The train is positioned in front of a building, and",
    "The image depicts a narrow alleyway between two buildings, with a brick wall on one side and a stone wall on the other. The alley",
    "The image depicts a busy restaurant kitchen with three chefs working together to prepare food. They are standing behind a counter, surrounded by various kitchen equipment and",
    "The image features a large, lush green field filled with a herd of sheep grazing on the grass. There are at least 14 sheep visible",
    "The image depicts a bathroom with a white sink and mirror on the wall. The sink is located near the center of the room, and the mirror",
    "The image features a man and a woman walking down a street, possibly in a market area. The man is wearing a black tank top, while the woman",
    "The image features a red stop sign with a street sign attached to it. The stop sign is located on a pole, and the street sign is positioned above",
    "The image features a wooden bench situated in a park, surrounded by trees. On the bench, there is a bottle of lotion, possibly a",
    "The image features a young girl standing in a park, wearing a red outfit and holding a red bicycle. She is positioned near a ben",
    "The image features a large sailboat docked at a pier, with its sails down. The boat is positioned in the middle of the scene,",
    "The image shows a group of people running on a track, with one man wearing a red hoodie and plaid pants leading the way. There",
    "The image features a man standing in a kitchen, preparing food on a counter. He is surrounded by various kitchen items, including a bowl, a kn",
    "The image captures a serene scene of a river at dusk, with the sun setting in the background. The water appears calm and reflects the sky",
    "The image features a large group of Canadian geese gathered in a grassy field. There are at least 14 geese visible in the scene, with",
    "The image features a group of four men standing together on a street, possibly participating in a protest or gathering. They are all wearing plaid sh",
    "The image features a close-up of a bouquet of red tulips in a vase. The tulips are arranged in a visually appe",
    "The image captures a beautiful sunset over a large body of water, with the sun setting behind the horizon. The sky is filled with vibrant colors",
    "The image features a large bird with a long beak walking through a grassy field. The bird appears to be a heron, and it is the main",
    "The image features a beautiful view of the ocean with a cloudy sky above. The water is calm, and the sky is filled with clouds, creating a ser",
    "The image features a red double-decker bus driving down a street, with several people walking on the sidewalk. One of the pedestrians is",
    "The image depicts a group of people sitting around a table, engaged in a meeting or discussion. There are at least nine people in the scene, with",
    "The image depicts a bathroom in the process of being remodeled. The toilet is situated in the middle of the room, surrounded by",
    "The image features a red double-decker bus driving down a city street, with several people standing on the top deck, enjoying the view. There are",
    "The image features a man wearing a white shirt and apron, standing in a kitchen and preparing food. He is holding a pizza in his",
    "The image features a bathroom with a white bathtub and a shower stall. The bathtub is located in the center of the room,",
    "The image features a person wearing a yellow jacket, standing in a snowy field near a building. The person appears to be walking through the snow,",
    "The image depicts a busy city street with a man walking down the sidewalk, holding an umbrella to protect himself from the rain. He is",
    "The image captures a young man in a red shirt and black shorts jumping over a hurdle during a track and field event. He is",
    "The image features three women standing together, each holding a sign. They appear to be protesting or participating in a demonstration. The women are positioned",
    "The image features a gray and white fighter jet flying high in the sky. The jet is flying with its wings spread out, showcasing its impressive",
    "The image features a bathroom with two sinks, each accompanied by a mirror above them. The sinks are positioned side by side, and the mirror",
]
